# Generated by Django 3.2.7 on 2021-09-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_clone.comment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_clone.like'),
        ),
    ]
