# Generated by Django 3.2.7 on 2021-09-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_clone', '0002_auto_20210912_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
