# Generated by Django 3.2.7 on 2021-09-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_clone', '0004_auto_20210913_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='liker',
            new_name='likes',
        ),
    ]
