# Generated by Django 3.2.6 on 2021-09-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_clone', '0006_auto_20210913_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram_clone.image'),
        ),
    ]
